version: '3.9'

services:
  postgres:
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env
    image: postgres:15.1-alpine
    networks:
      - pg-notify-test

networks:
  pg-notify-test:
    name: pg-notify-test
